# Generated by Django 3.2.4 on 2021-06-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('date',)},
        ),
    ]
